### ISSUE TITLE
update Enum, so flags can be (value,doc) not just value

### ISSUE THREAD

**Issue by arekbulski** [construct/construct#696]
This is to allow KSY exporter to generate Enums that preserve doc tags on values. Like in
```yaml
enums:
  animal:
    4:
      id: dog
      doc: A member of genus Canis.
      -orig-id: MH_CANINE
    7:
      id: cat
      doc: Small, typically furry, carnivorous mammal.
      -orig-id: MH_FELINE
    12: chicken
```
If you look at [Enum docs](https://construct.readthedocs.io/en/latest/api/mappings.html#construct.Enum) the syntax is like:
```py
Enum(Byte, one=1, two=2, four=4, eight=8)
```
but I could make it like:
```py
Enum(Byte, dict(value=1, id="one", origid="...", docs="...") ...)
```
Letting you know, @greycat . Honestly I dont like this feature, and most likely wont implement it, but if you would request it, then I would give it more consideration.
